services:
  db:
    image: postgres:14.1-bullseye
    ports:
      - "5432:5432"
    volumes:
      - prox-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=prox-backend
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
  db2:
    image: postgres:14.1-bullseye
    ports:
      - "5434:5432"
    volumes:
      - prox-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=prox-backend
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata2
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: on-failure
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=/
  localstack:
    image: localstack/localstack:1.3.0
    environment:
      SERVICES: S3
      START_WEB: 0
      DEFAULT_REGION: eu-central-1
    ports:
      - "4566:4566"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  prox-db-data: {}
  keycloak-db-data: {}