apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "prox-backend.fullname" . }}-view-secrets
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      {{- if .Values.config.existingSecret }}
      - {{ .Values.config.existingSecret }}
      {{- else }}
      - {{ include "prox-backend.fullname" . }}
      {{- end }}
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "prox-backend.fullname" . }}-view-configmaps
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      {{- if .Values.config.existingConfigMap }}
      - {{ .Values.config.existingConfigMap }}
      {{- else }}
      - {{ include "prox-backend.fullname" . }}
      {{- end }}
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "prox-backend.fullname" . }}-view
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: prox-backend-view-configmaps
subjects:
  - kind: ServiceAccount
    name: {{ include "prox-backend.serviceAccountName" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "prox-backend.fullname" . }}-view-secrets
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: prox-backend-view-secrets
subjects:
  - kind: ServiceAccount
    name: {{ include "prox-backend.serviceAccountName" . }}
