kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "prox-backend.fullname" . }}
rules:
  - apiGroups: [ "", "extensions", "apps" ]
    resources: [ "configmaps", "pods", "services", "endpoints", "secrets" ]
    verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "prox-backend.fullname" . }}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "prox-backend.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "prox-backend.serviceAccountName" . }}