{{- if not .Values.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prox-backend.fullname" . }}
  labels:
    {{- include "prox-backend.labels" . | nindent 4 }}
type: Opaque
data:
  dbPassword: {{ include "prox-backend.superUserPassword" . }}
  replicationUserPassword: {{ include "prox-backend.replicationUserPassword" . }}
  {{- end }}
