cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY:accesskey}
      secret-key: ${AWS_SECRET_KEY:secretkey}
    s3:
      endpoint: http://127.0.0.1:4566
    region: us-east-1
spring:
  datasource:
    password: prox-backend
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: prox-backend
  rabbitmq:
    host: ${RABBITMQ_HOST:127.0.0.1}
    port: ${RABBITMQ_PORT:5672}
logging:
  level:
    "org.hibernate.SQL": DEBUG
    "org.hibernate.type.descriptor.sql.BasicBinder": TRACE