keycloak:
  realm: innovation-hub-bergisches-rheinland
  client-id: prox-backend
  auth-server-url: https://login.aws.innovation-hub.de/auth
  credentials:
    secret: ${KEYCLOAK_SECRET:}
server:
  port: 8080
  compression:
    enabled: true
  forward-headers-strategy: framework
cloud:
  aws:
    region: eu-central-1
    credentials:
      access-key: ${AWS_ACCESS_KEY:}
      secret-key: ${AWS_SECRET_KEY:}
    s3:
      bucket: ${AWS_S3_BUCKET:prox}
spring:
  application:
    name: prox-backend
  datasource:
    password: ${DB_PASSWORD:prox-backend}
    url: jdbc:postgresql://prox-db:5432/postgres
    username: ${DB_USER:prox-backend}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  mvc:
    problemdetails:
      enabled: true
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:admin}
    password: ${RABBITMQ_PASSWORD:admin}
    virtual-host: "/"
    listener:
      simple:
        # TODO: We might need a more sophisticated approach
        default-requeue-rejected: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.aws.innovation-hub.de/auth/realms/innovation-hub-bergisches-rheinland