cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY:aws-access-key}
      secret-key: ${AWS_SECRET_KEY:aws-secret-key}
    s3:
      endpoint: http://localhost:4566
    region: eu-central-1
spring:
  datasource:
    password: prox-backend
    url: jdbc:postgresql://localhost:5432/prox-db
    username: prox-backend
