cloud:
  aws:
    region: us-east-1
    s3:
      endpoint: http://localstack:4566
spring:
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
  datasource:
    url: jdbc:postgresql://prox-db:5432/postgres