{{- if not .Values.config.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prox-backend.fullname" . }}
  labels:
    {{- include "prox-backend.labels" . | nindent 4 }}
data:
  spring.application.name: {{ include "prox-backend.fullname" . }}
  spring.cloud.kubernetes.secrets.enabled: "true"
  {{- end }}
